site_name: Rin Docs

theme:
  name: readthedocs
  locale: en

plugins:
  - search:
      lang: en

repo-url: https://github.com/No767/Rin-Docs
repo_name: GitHub

markdown_extensions:
  - toc:
      permalink: true
  - attr_list