site_name: Rin Docs

theme:
  name: readthedocs

plugins:
  - search:
      lang: 
        - en

markdown_extensions:
    - toc:
        permalink: True

repo_url: https://github.com/No767/Rin-Docs
repo_name: GitHub
edit_uri: blob/master/docs/

nav:
  - 'Commands':
    - 'Commands': 'rin-commands.md'
  - 'Contributing': 
    - 'Contributing': 'contributing-to-rin.md'
  - 'Terms and Conditions':
    - 'Art Assets': 'art-assets.md'
  - 'About':
    - 'About Rin': 'about-rin.md'
    - 'Project Structure': 'project-structure.md'
